### PR TITLE
implemented binary search in python

### PR DESCRIPTION
**Pull request by ShyamSunder149**
I have implemented Binary search algorithm using python and I have done this contribution as a part of Hacktoberfest

### CODE REVIEW

**Comment by anishaswain** [comment]
@ShyamSunder149 Can you please add a Python folder inside Search folder so that other people can add their languages as well?

**Comment by ShyamSunder149** [comment]
yeah will do that

**Comment by ShyamSunder149** [comment]
please check it now

**Comment by ShyamSunder149** [comment]
Can you please add this project to hacktoberfest as this repo is showing as not participating in hacktoberfest

**Review by Nerdcode — APPROVED** [review]

**Pull request merged**
